### ISSUE TITLE
Packed SIMD gcc, binutils

### ISSUE THREAD

**Issue by jjscheel** [riscv-admin/dev-partners#22]
### Technical Group

Other

### ratification-pkg

Packed SIMD

### Technical Liaison

Kevin Chen

### Task Category

Compilers/Toolchain

### Task Sub Category

- [X] gcc
- [X] binutils
- [ ] gdb
- [ ] intrinsics
- [ ] Java
- [ ] KVM
- [ ] ld
- [ ] llvm
- [ ] Linux kernel
- [ ] QEMU
- [ ] Spike

### Ratification Target

4Q2023

### Statement of Work (SOW)

**Component names:**

**Requirements:**
  (prose describing what has to be done and what the end result is)

**Deliverables:**
  - Component_1 and changes expected.
  - Component_2 and changes expected.
  ...

**Acceptance Criteria:**
  - Component_1 and measured result.
  - Component_2 and measured result.
  ...

**Projected timeframe:** (best guess date)

**SOW Signoffs:** (delete those not needed)
  - Task group liaison sign-off date:
  - Development partner sign-off date:
  - ACT SIG sign-off date (if ACT work):
  - Toolchains & Runtimes sign-off date (if gcc, LLVM, binutils, gdb work):
  - Privileged SW HC sign-off date (if QEMU, KVM, kernel, or OS work):
  - Application & Tools HC sign-off date (if POC or toolchain/library work):

### Waiver

- [ ] Freeze
- [ ] Ratification

**Comment by jjscheel** [comment]
Good to know.  Thanks.

But the spec hasn't even been reviewed internally and thus may change!

**Comment by ChunyuLiao** [comment]
llvm has some patches under review, but are not active.
[RISCV] Implement the MC layer support of P extension https://reviews.llvm.org/D95588
[RISCV] Support experimental 'P' extension 0.9.11 https://reviews.llvm.org/D108189
[RISCV] Implement intrinsics for P extension https://reviews.llvm.org/D99158
[RISCV] Add vector types to GPR for P extension and explict type to existing codegen patterns https://reviews.llvm.org/D100288
[RISCV] Support Zbpbo extension v0.9.11 https://reviews.llvm.org/D128604

**Comment by pz9115** [comment]
P-ext TG has been active recently， discussing some instruction design in the community, waiting for their update.

https://lists.riscv.org/g/tech-p-ext/topic/102843596#268

**Comment by pz9115** [comment]
Agree!

**Comment by jjscheel** [comment]
I reached out to the P-Ext Chair and they will indeed need help with toolchain.  I need to get them enabled.  Work is on my end.

**Comment by pz9115** [comment]
John Hauser sent a new version draft specification for Packed SIMD, still wait it move into a stable specification，maybe need take a few month.

https://lists.riscv.org/g/tech-p-ext/message/291

**Comment by jjscheel** [comment]
Specification work continues by John Hauser.

**Comment by jjscheel** [comment]
@fuhle044, please see the [first entry](https://github.com/riscv-admin/dev-partners/issues/22#issue-1629439233) for the issue (this is our SOW) and propose new text (as a comment) for the Requirements, Deliverables, and Acceptance Criteria sections.

**Comment by jjscheel** [comment]
@lazyparser, am I correct in assuming you plan on working on LLVM too?  Are there any other pieces besides these 3?

**Comment by fuhle044** [comment]
Yes, LLVM will be included.

-rich

**Comment by pz9115** [comment]
We have a SOW here, and need Rich help to add the P spec link that need to be implement.

https://docs.google.com/document/d/1dCnLq8eSgOnD-bYrembB5aU4IVejn2q4OSJceVRIJpU/edit?usp=sharing

**Comment by jjscheel** [comment]
@pz9115, @fuhle044, I have taken the SOW information and put it into the first entry above [SOW](https://github.com/riscv-admin/dev-partners/issues/22#issue-1629439233).  Please review and provide any comments.

**Comment by pz9115** [comment]
We found a draft doc here https://lists.riscv.org/g/tech-p-ext/files/Drafts/RVP-baseInstrs-A-010.pdf, but it still need add encoding and some instruction description to make sure we can implement it clear in toolchain part.

**Comment by pz9115** [comment]
Keep waiting specificaction doc.

**Comment by jjscheel** [comment]
I talked with Rich Fuhler at RISC-V Summit NA and encouraged him to update Asciidoc version of document with all other design information.  Offered to help as needed.

I did not get a target date for this work completing, but they understand that it's needed.

**Comment by pz9115** [comment]
Find the new draft p-ext instructions and encoding docs in https://www.jhauser.us/RISCV/ext-P/

Now working on the Binutils part, plans to complete it within the next month

- [ ] Add instructions endocing marco.
- [ ] Support register pair feature.
- [ ] Support register operands check.
- [ ] Add testcases.

https://github.com/ruyisdk/riscv-binutils/tree/p-dev

**Comment by jjscheel** [comment]
@pz9115, I think we have to be a little careful with the document you found given that it's not in the official repo for the spec.  But, it's likely a safe starting place for your work.

**Comment by pz9115** [comment]
Still work in progress.

**Comment by jjscheel** [comment]
I've not seen any substantial movement toward a spec here.  Have you @pz9115?

**Comment by pz9115** [comment]
Updated binutils implements into version [0.14](https://www.jhauser.us/RISCV/ext-P/)
https://github.com/ruyisdk/riscv-binutils/commit/f5371c5ef730eb3ff81aa900e12a05509127403f

**Comment by pz9115** [comment]
Fixed building problems, now writing testcases for nonpaired instructions.

**Comment by jjscheel** [comment]
@pz9115 and @gsterlin, I've updated the title to include QEMU.  The main description (first entry) did already include it.  S, I think we're good to go.

**Comment by pz9115** [comment]
Sync the qemu repository link: https://github.com/mollybuild/qemu/tree/riscv-to-apply.next
and also update the LLVM work in progress: https://github.com/realqhc/llvm-project/tree/p-mc
	 	https://github.com/llvm/llvm-project/pull/123271

**Comment by pz9115** [comment]
Still work in progress.

**Comment by pz9115** [comment]
Update immediate implement in binutils, WIP
https://github.com/ruyisdk/riscv-binutils/commit/19d93c476d210b11060398992b99fd7f9688cc70

**Comment by pz9115** [comment]
Tested nopaired instructions on qemu, worked as expected. Now develop on paired instructions part.

**Comment by pz9115** [comment]
Found missing encoding for some instructions, reported to the TG, WIP
https://lists.riscv.org/g/tech-p-ext/topic/new_p_encodings_document/113317555

**Comment by pz9115** [comment]
Update encoding with new version 0.15
https://lists.riscv.org/g/tech-p-ext/topic/new_p_encodings_document/113317555

Discussed MAC instructions including or not
https://lists.riscv.org/g/tech-p-ext/topic/inclusion_of_saturating_mac/113479784

**Comment by pz9115** [comment]
WIP

**Comment by pz9115** [comment]
Rebased up to binutils 2.44 and fix up bugs

https://github.com/ruyisdk/riscv-binutils/commits/p-dev/

**Comment by pz9115** [comment]
Currently finish all Binutils instructions development, 
https://github.com/ruyisdk/riscv-binutils/commits/p-dev/

and sync to p-ext TG
https://lists.riscv.org/g/tech-p-ext/topic/binutils_process/114163712

**Comment by pz9115** [comment]
Prepared a draft version for p intrinsic， now starting gcc development

https://github.com/pz9115/rvp-intrinsic-doc/blob/main/source/simd.md

**Comment by pz9115** [comment]
Finished base framework of gcc part:

https://github.com/ruyisdk/riscv-gcc/tree/p-dev

**Comment by pz9115** [comment]
Update intrinsic defination, more discussion is in progress:
https://lists.riscv.org/g/tech-p-ext/message/742

Finished QEMU part for current instructions:
https://lists.riscv.org/g/tech-p-ext/message/743

**Comment by pz9115** [comment]
Finished gcc intrinsics API support, now doing testing job for it.
https://github.com/ruyisdk/riscv-gcc/commits/p-dev/

**Comment by pz9115** [comment]
Finished test work. Preparing ASCII spec doc for ARC reviewing.

**Comment by pz9115** [comment]
The current implementation status of the draft on the toolchain has been compiled and synchronized to the riscv-p-spec repository.
https://github.com/riscv/riscv-p-spec/commit/facd5fdc17a36c2eae6d62057fd20200d63859c6

**Comment by pz9115** [comment]
Updated binutils encoding implement https://github.com/ruyisdk/riscv-binutils/commit/76d1d1e40e991fbc08072f95118ed1bd2262c9e3, now the draft version coming into 018 https://www.jhauser.us/RISCV/ext-P/, doing toolchain part upgrade in progress.

**Comment by pz9115** [comment]
Update P-draft specification in adoc format

https://github.com/riscv/riscv-p-spec

**Comment by jjscheel** [comment]
Works continues as part of the normal specification development process for the Packed SIMD Specification in the TG.  Details are available in Jira [RVS-1135](https://riscv.atlassian.net/browse/RVS-1135).

Closing for DevPartners.
