### ISSUE TITLE
Atomics ACT

### ISSUE THREAD

**Issue by jjscheel** [riscv-admin/dev-partners#25]
### Technical Group

Architecture Test SIG

### ratification-pkg

Atomics

### Technical Liaison

Allen Baum

### Task Category

Arch Tests

### Task Sub Category

- [ ] gcc
- [ ] binutils
- [ ] gdb
- [ ] intrinsics
- [ ] Java
- [ ] KVM
- [ ] ld
- [ ] llvm
- [ ] Linux kernel
- [ ] QEMU
- [ ] Spike

### Ratification Target

3Q2023

### Statement of Work (SOW)

SOW: [link](https://docs.google.com/document/d/1nr1jc_SvtsCdfr__gsrAk2gX0Rz0IFuHPgEiN3afnxM/)

**SOW Signoffs:**
  - Task group liaison sign-off date:
  - Development partner sign-off date:
  - ACT SIG sign-off date (if ACT work):

### Waiver

- [ ] Freeze
- [ ] Ratification

### Pull Request Details

[PR #1 of 2](https://github.com/riscv-non-isa/riscv-arch-test/pull/357) - Merged
[PR #2 of 2](https://github.com/riscv-software-src/riscv-ctg/pull/69) - Merged
[PR #3 of 2](https://github.com/riscv-non-isa/riscv-arch-test/pull/439) - Replaced by #4
[PR #4 of 2](https://github.com/riscv-non-isa/riscv-arch-test/pull/600) - In review

**Comment by UmerShahidengr** [comment]
[Ahad Ali](https://github.com/ahadali-10x) from 10xEngineers will be working on this issue.

**Comment by jjscheel** [comment]
@UmerShahidengr, good to know.  

Would you kindly make sure that Ahad does the following?

- [ ] Gets a Portal Id
- [ ] Joins the (DevPartners Group)[https://lists.riscv.org/g/dev-partners/topics]
- [ ] Puts his GitHub id in his profile per the (discussion)[https://lists.riscv.org/g/dev-partners/topic/risc_v_profile_update/97658653]

Then, I will add him to the project and issue.

**Comment by jjscheel** [comment]
@ahadali-10x, you should have an invitation to the project, please accept so that I can assign this issue to you.

**Comment by ahadali-10x** [comment]
@jjscheel, I haven't received an invitation to the project.

**Comment by jjscheel** [comment]
Please try looking on GitHub, either:
https://github.com/riscv-admin/ or 
https://github.com/orgs/riscv-admin/teams/riscv-devpartner-partners

You should see it on the top of the page.  Also, you should have received an email notification per your GitHub settings.

**Comment by ahadali-10x** [comment]
I have accepted the invitation.

**Comment by jjscheel** [comment]
I have assigned you to this issue!  THANKS!!!

**Comment by UmerShahidengr** [comment]
Update: Apr 25th, 2023 => The planning phase of this project has been completed, this is the test plan for the viewers to review: [Test plan Pointer Masking Ext](https://docs.google.com/spreadsheets/d/19mssZzgzTSKae9nt-q0ukRNy9XoAA-F792yE2SVAAvY/edit?usp=sharing)
Goal for next week: Develop the skeleton code (Basic R/W access to the Pointer masking CSR regs) according to the ACT template, and run it on Spike via riscof.

**Comment by UmerShahidengr** [comment]
Update May 7th, 2023 ⇾ Progress has been slow so far as @ahadali-10x is learning the riscof tool, structure of existing ACTs. The initial tests will be developed till next week.

PS: Our completion date for this project is still 2023Q2, so we will accelerate this task, our 1st PR will be submitted before the next week, hopefully.

**Comment by UmerShahidengr** [comment]
Update May 23rd, 2023 => The initial set of tests are ready, and [available here](https://github.com/ahadali-10x/riscv-arch-test/tree/atomic_ACTs/riscv-test-suite/rv32i_m/A/src). PR will be submitted in 2-3 days after some fine tuning.

**Comment by jjscheel** [comment]
Excellent news, @UmerShahidengr!  Marking as Development Complete.

**Comment by ahadali-10x** [comment]
No, more PRs are expected. These tests are for RV32. Tests for RV64 are remaining.

**Comment by jjscheel** [comment]
Ok.  Thanks, @ahadali-10x!

**Comment by UmerShahidengr** [comment]
Update ⇾ June 12th, 2023:
Next major commit (RV64 tests) is expected this week

**Comment by jjscheel** [comment]
Thanks, Umer.  Removed from this week's agenda.  Will get update in next meeting.

**Comment by UmerShahidengr** [comment]
Update ⇾ July 11th, 2023
Coverpoints and coverage is almost finished. This project will be completed after submitting the coverage reports and coverpoints this week

**Comment by ahadali-10x** [comment]
Here is the PR link: https://github.com/riscv-software-src/riscv-ctg/pull/69

**Comment by jjscheel** [comment]
Got it.  Updated the summary in first entry.  THANKS!

**Comment by UmerShahidengr** [comment]
Update ⇾ August 15th, 2023:
@allenjbaum has been reviewing this PR, there is not much update on CTG PR (https://github.com/riscv-software-src/riscv-ctg/pull/69) as review process has not been started yet, but ACTs have been reviewed. There are some minor bugs in macro definition which are yet to be fixed. Hopefully @ahadali-10x will fix it this week

**Comment by Abdulwadoodd** [comment]
Hi @jjscheel ,

RISC-V CTG PR - to generate atomic ACTs and its coverage reports - has been merged.
PR Link: https://github.com/riscv-software-src/riscv-ctg/pull/69

FYI: @UmerShahidengr, @ahadali-10x

**Comment by UmerShahidengr** [comment]
@jjscheel there is no PR left to be made. The one in arch-tests is in review process and it has everything required from our side, hopefully it will also be merged soon.

**Comment by UmerShahidengr** [comment]
Update ⇾ September 12th, 2023
No update on this. PR is still in review process.

**Comment by jjscheel** [comment]
@allenjbaum, can your provide any feedback or outlook here?

**Comment by UmerShahidengr** [comment]
Update ⇾ September 26th, 2023
PR has been approved, so work is complete.

**Comment by jjscheel** [comment]
Nice work, @UmerShahidengr and @ahadali-10x!

@allenjbaum, please confirm your sign-off of this item so that we can consider done.

**Comment by allenjbaum** [comment]
I have marked it done. Hey, that should be in the tech newsletter, eh?

**Comment by jjscheel** [comment]
Thanks, @allenjbaum!

Yes, I opened a Newsletter item: [#19](https://github.com/riscv-admin/tech-newsletter/issues/19).

**Comment by allenjbaum** [comment]
Well, what is there is good, but it doesn't meet the SOW.
1: No tests for unaligned atomics (which are supposed to trap, & therefore set RVTEST_MTRAP_ROUTINE)
There are actually two different trap causes: address misalign and access fault. Access fault has higher priority, and this can be tested by trying to store at an address that doesn't allow reads or writes (either a malformed address, or PMP or PTE permissions). If we're not counting on S or U modes being implemented, then we can only test this by using a physical address whose upper bits are non-zero. If we don't know the size of the PA, just set the PA to -1 The test should account for the value being intialized by explicitly writing each unaligned half, and adjusting the signature address before to point to the unaligned address and after to be the aligned value.

2. There is also no coverage of LR/SC. While we can't test what happens with an interfering access, we can test what happens in all the other cases mentioned in the spec: too many instructions between LR and SC, load/store between LR and SC (both non-interfering and interfering, where interfering is accessing any byte in the implementation-defined reservation-set size, including when an unaligned address overlaps), LRs or SCs to different addresses between otherwise well formed LR/SC pairs, trapping between LR and SC (e.g. ecall or bkpt) etc.

**Comment by jjscheel** [comment]
@allenjbaum, thanks for raising this.  I've set this back to Signoff state and we likely will adjust more in the future.

@UmerShahidengr, I believe you agreed to take a look at this in the Arch Test SIG call today.  I'll assign to you for now.  Feel free to re-assign as needed.

**Comment by UmerShahidengr** [comment]
Thank you @jjscheel , this will be rectified before our next meeting.

**Comment by jjscheel** [comment]
No worries, @UmerShahidengr.  THANKS!

**Comment by UmerShahidengr** [comment]
Update ⇾ November 28th, 2023
[Here](https://docs.google.com/spreadsheets/d/1deo-9q2epOCaQJ5c4UlReIWmM8CHqvOWpnG7frYAVS0/edit#gid=0) is the test plan for LR/SC tests. We will be following this test plan and will deliver the tests before the next meeting.

**Comment by UmerShahidengr** [comment]
Update ⇾ December 12th, 2023
The ACTs of LR/SC have been developed by @ahadali-10x and are in internal review stage. Tests will be available in the next week, but coverpoint definitions will take some time.

**Comment by allenjbaum** [comment]
I've added some other test coverpoints to the test plan. (in column F)

**Comment by UmerShahidengr** [comment]
Update ⇾ January 30th, 2024
Basic LR/SC tests are ready. coverpoint definitions are left. Expecting to deliver it soon.

**Comment by UmerShahidengr** [comment]
Here is the testplan: https://docs.google.com/spreadsheets/d/1deo-9q2epOCaQJ5c4UlReIWmM8CHqvOWpnG7frYAVS0/edit#gid=0

**Comment by UmerShahidengr** [comment]
Update ⇾ March 5th, 2024
LR/SC tests have been delivered, and are available in [this PR](https://github.com/riscv-non-isa/riscv-arch-test/pull/439). This SoW will be completed once this PR will be merged.

**Comment by jjscheel** [comment]
Thanks, @UmerShahidengr.  I've updated the description.

**Comment by UmerShahidengr** [comment]
Update ⇾ April 2nd, 2024
LR/SC PR is yet to be merged. @allenjbaum has been notified to review it.

**Comment by jjscheel** [comment]
Thanks, Umer.

**Comment by UmerShahidengr** [comment]
Update ⇾ April 18th, 2024
@allenjbaum has reviewed LR/SC tests, these tests will be updated before the nxt meeting.

**Comment by UmerShahidengr** [comment]
Update June 11th, 2024:
LR/SC tests were shelved due to the lack of resources in this quarter, we will resume this one in the next quarter

**Comment by jjscheel** [comment]
Thanks for update, @UmerShahidengr.  Let's plan for update in July.

**Comment by UmerShahidengr** [comment]
The updated LR/SC tests have been released. PR Link: https://github.com/riscv-non-isa/riscv-arch-test/pull/600

**Comment by jjscheel** [comment]
Thanks, @UmerShahidengr. Does this new PR replace this one: https://github.com/riscv-non-isa/riscv-arch-test/pull/439?

**Comment by UmerShahidengr** [comment]
@jjscheel yes, the older one will be closed.

**Comment by jjscheel** [comment]
Work being drive by Certification Test Plan WG and ACT SIG. Details can be found in the [Certification Implementation Tracking](https://docs.google.com/spreadsheets/d/1EuG4LV1TQDx4wTzYDWEAvq0fwaWjNuxenwDARZmrN-E/edit?gid=0#gid=0) spreadsheet.

Closing.
